# 사이트 기본 설정
theme: jekyll-theme-chirpy
lang: ko
timezone: Asia/Seoul

# 블로그 정보 k
title: "차백의 개발 블로그"
tagline: "백엔드 개발자 도전기"
description: "자바, 스프링 부트캠프 학습 기록 및 성장 블로그"

# 주소 설정 
url: "https://sihwan0802.github.io"
github:
  username: sihwan0802

# 작성자 정보
social:
  name: "CHABack"
  links:
    - https://github.com/sihwan0802

# 테마 옵션
theme_mode: dark 
avatar: "/assets/img/avatar.jpg"
toc: true

# 배포 설정
paginate: 10
baseurl: ""

# Jekyll 엔진 설정 
kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

sass:
  style: compressed

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"
